language = "C"
header = "// Copyright (c) Tribufu. All Rights Reserved."
pragma_once = true
include_version = false
namespaces = []
using_namespaces = []
sys_includes = ["mintaka/prelude.h"]
includes = []
no_includes = true
cpp_compat = false
braces = "NextLine"
line_length = 100
tab_width = 4
documentation = true
documentation_style = "doxy"
style = "tag"

[defines]
"debug_assertions" = "MINTAKA_DEVEL"
"not(debug_assertions)" = "MINTAKA_RETAIL"
"panic = abort" = "MINTAKA_PANIC_ABORT"
"panic = unwind" = "MINTAKA_PANIC_UNWIND"
"proc_macro" = "MINTAKA_PROC_MACRO"
"target_arch = aarch64" = "MINTAKA_AARCH64"
"target_arch = arm" = "MINTAKA_ARM"
"target_arch = armV7" = "MINTAKA_ARMV7"
"target_arch = armv4t" = "MINTAKA_ARMV4T"
"target_arch = armv6" = "MINTAKA_ARMV6"
"target_arch = armv7a" = "MINTAKA_ARMV7A"
"target_arch = armv7s" = "MINTAKA_ARMV7S"
"target_arch = avr" = "MINTAKA_AVR"
"target_arch = bpfeb" = "MINTAKA_BPFEB"
"target_arch = bpfel" = "MINTAKA_BPFEL"
"target_arch = hexagon" = "MINTAKA_HEXAGON"
"target_arch = i386" = "MINTAKA_I386"
"target_arch = i586" = "MINTAKA_I586"
"target_arch = i686" = "MINTAKA_I686"
"target_arch = m68k" = "MINTAKA_M68K"
"target_arch = mips" = "MINTAKA_MIPS"
"target_arch = mipsel" = "MINTAKA_MIPSEL"
"target_arch = msp430" = "MINTAKA_MSP430"
"target_arch = powerpc" = "MINTAKA_POWERPC"
"target_arch = powerpc64" = "MINTAKA_POWERPC64"
"target_arch = powerpc64l" = "MINTAKA_POWERPC64L"
"target_arch = riscv32gc" = "MINTAKA_RISCV32GC"
"target_arch = s390x" = "MINTAKA_S390X"
"target_arch = sparc" = "MINTAKA_SPARC"
"target_arch = sparc64" = "MINTAKA_SPARC64"
"target_arch = thumbv4t" = "MINTAKA_THUMBV4T"
"target_arch = thumbv7a" = "MINTAKA_THUMBV7A"
"target_arch = thumbv7neon" = "MINTAKA_THUMBV7NEON"
"target_arch = wasm32" = "MINTAKA_WASM32"
"target_arch = wasm64" = "MINTAKA_WASM64"
"target_arch = x86" = "MINTAKA_X86"
"target_arch = x86_64" = "MINTAKA_X86_64"
"target_endian = big" = "MINTAKA_BIG_ENDIAN"
"target_endian = little" = "MINTAKA_LITTLE_ENDIAN"
"target_env = gnu" = "MINTAKA_GNU"
"target_env = msvc" = "MINTAKA_MSVC"
"target_env = musl" = "MINTAKA_MUSL"
"target_env = sgx" = "MINTAKA_SGX"
"target_family = unix" = "MINTAKA_UNIX"
"target_family = wasm" = "MINTAKA_WASM"
"target_family = windows" = "MINTAKA_MICROSOFT"
"target_feature = avx" = "MINTAKA_AVX"
"target_feature = avx2" = "MINTAKA_AVX2"
"target_feature = crt-static" = "MINTAKA_CRTSTATIC"
"target_feature = rdrand" = "MINTAKA_RDRAND"
"target_feature = sse" = "MINTAKA_SSE"
"target_feature = sse2" = "MINTAKA_SSE2"
"target_feature = sse4.1" = "MINTAKA_SSE41"
"target_has_atomic = 128" = "MINTAKA_ATOMIC_128"
"target_has_atomic = 16" = "MINTAKA_ATOMIC_16"
"target_has_atomic = 32" = "MINTAKA_ATOMIC_32"
"target_has_atomic = 64" = "MINTAKA_ATOMIC_64"
"target_has_atomic = 8" = "MINTAKA_ATOMIC_8"
"target_has_atomic = ptr" = "MINTAKA_ATOMIC_PTR"
"target_os = android" = "MINTAKA_ANDROID"
"target_os = dragonfly" = "MINTAKA_DRAGONFLY"
"target_os = freebsd" = "MINTAKA_FREEBSD"
"target_os = ios" = "MINTAKA_IOS"
"target_os = linux" = "MINTAKA_LINUX"
"target_os = macos" = "MINTAKA_MACOS"
"target_os = netbsd" = "MINTAKA_NETBSD"
"target_os = openbsd" = "MINTAKA_OPENBSD"
"target_os = windows" = "MINTAKA_WINDOWS"
"target_pointer_width = 16" = "MINTAKA_POINTER_16"
"target_pointer_width = 32" = "MINTAKA_POINTER_32"
"target_pointer_width = 64" = "MINTAKA_POINTER_64"
"target_vendor = apple" = "MINTAKA_APPLE"
"target_vendor = fortanix" = "MINTAKA_FORTANIX"
"target_vendor = pc" = "MINTAKA_MICROSOFT"
"target_vendor = unknown" = "MINTAKA_UNKNOWN"

[export]
include = []
exclude = []
item_types = ["enums", "structs", "typedefs", "functions"]
renaming_overrides_prefixing = false

[layout]
packed = "PACKED"
aligned_n = "ALIGNED"

[fn]
prefix = "NATIVE_API"
args = "horizontal"
must_use = "MUST_USE_FUNC"
no_return = "NO_RETURN"
rename_args = "None"
sort_by = "Name"

[struct]
rename_fields = "None"
must_use = "MUST_USE_STRUCT"
derive_constructor = true
derive_eq = false
derive_neq = false
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false

[enum]
rename_variants = "None"
add_sentinel = false
prefix_with_name = false
enum_class = false
derive_helper_methods = false
derive_const_casts = false
derive_mut_casts = false
must_use = "MUST_USE_ENUM"
derive_tagged_enum_destructor = false
derive_tagged_enum_copy_constructor = false
derive_tagged_enum_copy_assignment = false
private_default_tagged_enum_constructor = false

[const]
allow_static_const = true
allow_constexpr = false
sort_by = "Name"

[macro_expansion]
bitflags = true

[parse]
parse_deps = true
include = []
exclude = []
clean = false
extra_bindings = []

[parse.expand]
crates = []
all_features = true
default_features = true
features = []
